name: Test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        php-version: [ 8.3, 8.4, 8.5 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: gmp

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpunit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
